'use strict'

class CSSRule {
	constructor() {
		this.parentRule = null;
		this.parentStyleSheet = null;		
	}
}

const UNKNOWN_RULE = 0;                 // obsolete
const STYLE_RULE = 1;
const CHARSET_RULE = 2;                 // obsolete
const IMPORT_RULE = 3;
const MEDIA_RULE = 4;
const FONT_FACE_RULE = 5;
const PAGE_RULE = 6;
const KEYFRAMES_RULE = 7;
const KEYFRAME_RULE = 8;
const MARGIN_RULE = 9;
const NAMESPACE_RULE = 10;
const COUNTER_STYLE_RULE = 11;
const SUPPORTS_RULE = 12;
const DOCUMENT_RULE = 13;
const FONT_FEATURE_VALUES_RULE = 14;
const VIEWPORT_RULE = 15;
const REGION_STYLE_RULE = 16;

const rules = {
	UNKNOWN_RULE,
	CHARSET_RULE,
	IMPORT_RULE,
	MEDIA_RULE,
	FONT_FACE_RULE,
	PAGE_RULE,
	KEYFRAMES_RULE,
	KEYFRAME_RULE,
	MARGIN_RULE,
	NAMESPACE_RULE,
	COUNTER_STYLE_RULE,
	SUPPORTS_RULE,
    DOCUMENT_RULE,
    FONT_FEATURE_VALUES_RULE,
    VIEWPORT_RULE,
    REGION_STYLE_RULE,
};

Object.assign(CSSRule.prototype, rules)
Object.assign(CSSRule, rules)
export {
	UNKNOWN_RULE,
	CHARSET_RULE,
	IMPORT_RULE,
	MEDIA_RULE,
	FONT_FACE_RULE,
	PAGE_RULE,
	KEYFRAMES_RULE,
	KEYFRAME_RULE,
	MARGIN_RULE,
	NAMESPACE_RULE,
	COUNTER_STYLE_RULE,
	SUPPORTS_RULE,
    DOCUMENT_RULE,
    FONT_FEATURE_VALUES_RULE,
    VIEWPORT_RULE,
    REGION_STYLE_RULE,
}
export default CSSRule;